# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "ecobot40"
  limits:
    linear: [1.2, 1.5] # velocity, acceleration
    angular: [0.6, 0.6]
  profile: # Robot profile is modelled as a circle
    footprint: 0.5
    vicinity: 0.6
  reversible: False
  battery_system:
    voltage: 24.0
    capacity: 40.0
    charging_current: 26.4
  mechanical_system:
    mass: 80.0
    moment_of_inertia: 20.0
    friction_coefficient: 0.20
  ambient_system:
    power: 20.0
  cleaning_system:
    power: 760.0
  recharge_threshold: 0.05
  recharge_soc: 1.0
  publish_fleet_state: True
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: False
    clean: False # deprecated, now replace as custom action
    finishing_request: "nothing"
    action_categories: ["clean", "manual_control"]

# Ecobot CONFIG =================================================================

robots:
  ecobot40_1:
    ecobot_config:
      base_url: "http://10.7.5.88:8080"
      max_delay: 30.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
      filter_waypoints: True
      cleaning_task_prefix: "" # the prefix of the cleaning task created
      active_cleaning_config: "light_cleaning" # the cleaning config used during cleaning
      inactive_cleaning_config: "no_cleaning" # the cleaning config used during navigation
    rmf_config:
      robot_state_update_frequency: 0.5
      max_merge_lane_distance: 15.0 # means how far will the robot diverge from the defined graph
      charger:
        waypoint: "tinyRobot1_charger"

# TRANSFORM CONFIG =============================================================
# For computing transforms between Ecobot and RMF coordinate systems

# TRANSFORM CONFIG =============================================================
# For computing transforms between Ecobot and RMF coordinate systems
# Format robot_map: {rmf_map_name: rmf_map, transform: [tx,ty,r,s] }
# Format robot_map: {rmf_map_name: rmf_map, reference_coordinates: 
#                                 {rmf: [[x, y]....], rmf: [[x, y]....]}}
rmf_transform:
  mock_test_robot_map:
    rmf_map_name: "L1"
    transform: [1.33, 0.057, -1.598, 0.049] # This is obtained from traffic-editor
  ## User can also provide a pair of "reference_coordinates"
  # mock_test_robot_map2:
  #   rmf_map_name: "L1"
  #   reference_coordinates:
  #     rmf: [[33.11, -18.99],
  #           [111.3, -19.06],
  #           [86.16, -19.02],
  #           [24.68, -19.08] ]
  #     robot: [ [3876, 741],
  #               [2293, 703],
  #               [2816, 710],
  #               [4058, 747] ]
